#config_version=6
# GEMINI

mode:
  start_events: ball_starting{current_player.replay_mode == 1}
  stop_events: ball_ending
  priority: 200


event_player:
  player_score{value>current_player.replay_level_1 and prev_value<=current_player.replay_level_1}:
    replay
  player_score{value>current_player.replay_level_2 and prev_value<=current_player.replay_level_2}:
    replay
  player_score{value>current_player.replay_level_3 and prev_value<=current_player.replay_level_3}:
    replay