#config_version=6
# GEMINI

################################## Light_Player

light_player:
  mode_attract_started:
    l_canplay_2: on
  mode_attract_started{machine.player1_score>100000}:
    l_player1_rollover: on
  mode_attract_started{machine.player2_score>100000}:
    l_player2_rollover: on



  mode_attract_started{machine.match_number == 10}:
    l_match_10: on
  mode_attract_started{machine.match_number == 20}:
    l_match_20: on
  mode_attract_started{machine.match_number == 30}:
    l_match_30: on
  mode_attract_started{machine.match_number == 40}:
    l_match_40: on
  mode_attract_started{machine.match_number == 50}:
    l_match_50: on
  mode_attract_started{machine.match_number == 60}:
    l_match_60: on
  mode_attract_started{machine.match_number == 70}:
    l_match_70: on
  mode_attract_started{machine.match_number == 80}:
    l_match_80: on
  mode_attract_started{machine.match_number == 90}:
    l_match_90: on
  mode_attract_started{machine.match_number == 0}:
    l_match_00: on

slide_player:
  mode_attract_started: att_match_slide

slides:
  att_match_slide:
    - type: text
      text: (machine|match_number)
