#config_version=6
# GEMINI

################################## Light_Player

light_player:
  mode_attract_started.1:  
    l_canplay_2: on
    l_player1: on
    l_player2: on
    gi_lights: on


  mode_attract_started{machine.match_num == 10}:
    l_match_10: on
  mode_attract_started{machine.match_num == 20}:
    l_match_20: on
  mode_attract_started{machine.match_num == 30}:
    l_match_30: on
  mode_attract_started{machine.match_num == 40}:
    l_match_40: on
  mode_attract_started{machine.match_num == 50}:
    l_match_50: on
  mode_attract_started{machine.match_num == 60}:
    l_match_60: on
  mode_attract_started{machine.match_num == 70}:
    l_match_70: on
  mode_attract_started{machine.match_num == 80}:
    l_match_80: on
  mode_attract_started{machine.match_num == 90}:
    l_match_90: on
  mode_attract_started{machine.match_num == 0}:
    l_match_00: on


show_player:

  mode_attract_started:
    flash:
      speed: 4
      show_tokens:
        led: l_start_button 
    attract_lights:
      loops: -1

  mode_attract_started{machine.player1_score>=100000 and machine.player1_score<200000}:
    on:
      show_tokens:
        led: l_player1_rollover
  mode_attract_started{machine.player2_score>=100000 and machine.player2_score<200000}:
    on:
      show_tokens:
        led: l_player2_rollover
  mode_attract_started{machine.player1_score>=200000}:
    flash:
      speed: 3
      loops: -1
      show_tokens:
        led: l_player1_rollover
  mode_attract_started{machine.player2_score>=200000}:
    flash:
      speed: 3
      loops: -1
      show_tokens:
        led: l_player2_rollover


shows:
  attract_lights:
    - time: '+0.1'
      lights:
        l_bonus_1: on
        l_red_2: on
      coils:
        c_relay_1: pulse
    - time: '+1.0'
      lights:
        l_bonus_2: on
        l_bonus_1: off
        l_red_2: off
        l_white_2: on
      coils:
        c_relay_1: pulse
    - time: '+1.0'
      lights:
        l_bonus_3: on
        l_bonus_2: off
        l_white_2: off
        l_red_1: on
      coils:
        c_relay_1: pulse
    - time: '+1.0'
      lights:
        l_bonus_4: on
        l_bonus_3: off
        l_red_1: off
        l_white_1: on
      coils:
        c_relay_1: pulse
    - time: '+1.0'
      lights:
        l_bonus_5: on
        l_bonus_4: off
        l_white_1: off
        l_green_1: on
      coils:
        c_relay_1: pulse
    - time: '+1.0'
      lights:
        l_bonus_6: on
        l_bonus_5: off
        l_green_1: off
        l_yellow_1: on
      coils:
        c_relay_1: pulse
    - time: '+1.0'
      lights:
        l_bonus_7: on
        l_bonus_6: off
        l_yellow_1: off
        l_green_3: on
      coils:
        c_relay_1: pulse
    - time: '+1.0'
      lights:
        l_bonus_8: on
        l_bonus_7: off
        l_green_3: off
        l_yellow_2: on
      coils:
        c_relay_1: pulse
    - time: '+1.0'
      lights:
        l_bonus_9: on
        l_bonus_8: off
        l_yellow_2: off
        l_white_3: on
      coils:
        c_relay_1: pulse
    - time: '+1.0'
      lights:
        l_bonus_10: on
        l_bonus_9: off
        l_white_3: off
        l_green_2: on
      coils:
        c_relay_1: pulse
    - time: '+1.0'
      lights:
        l_bonus_10: off
        l_green_2: off
      coils:
        c_relay_1: pulse