#config_version=6
# GEMINI

################################## Light_Player

light_player:
  mode_attract_started:
    l_canplay_2: on
  mode_attract_started{machine.player1_score>100000}:
    l_player1_rollover: on
  mode_attract_started{machine.player2_score>100000}:
    l_player2_rollover: on



  mode_attract_started{machine.match_num == 10}:
    l_match_10: on
  mode_attract_started{machine.match_num == 20}:
    l_match_20: on
  mode_attract_started{machine.match_num == 30}:
    l_match_30: on
  mode_attract_started{machine.match_num == 40}:
    l_match_40: on
  mode_attract_started{machine.match_num == 50}:
    l_match_50: on
  mode_attract_started{machine.match_num == 60}:
    l_match_60: on
  mode_attract_started{machine.match_num == 70}:
    l_match_70: on
  mode_attract_started{machine.match_num == 80}:
    l_match_80: on
  mode_attract_started{machine.match_num == 90}:
    l_match_90: on
  mode_attract_started{machine.match_num == 0}:
    l_match_00: on


