#config_version=6
# GEMINI

mode:
  priority: 500
  start_events: ball_will_end{device.counters.bonus.value>0 and game.tilted == False}        #### only start counting if you have bonus
  stop_events: timer_mode_extend_complete                  #### end after pause after the last bonus is paid out
  use_wait_queue: true

queue_relay_player:                    #### tell ball_ending to wait until done counting bonus
  ball_ending:
    post: start_bonus_count
    wait_for: timer_mode_extend_complete 

################################## Timer

timers:
  motor_timer:
    control_events:
      - event: start_bonus_count
        action: start
    tick_interval: '0.153'
    direction: up

 
  mode_extend:
    control_events:
      - event: logicblock_bonus_count_complete
        action: start
    start_value: 1
    end_value: 0
    direction: down

################################## Counters

counters:
  bonus_count:
    starting_count: device.counters.bonus.value * device.counters.bonusx.value
    count_complete_value: 0
    direction: down
    count_events: timer_motor_timer_tick{ticks % 6 != 0}     #### don't count every 6th tick to to match score motor

      

################################## Variable Player - scoring

variable_player:
  counter_bonus_count_hit:
    score: 1000

################################## Coil Player - star and stop the actual motor

coil_player:
  start_bonus_count:
    c_score_motor: enable
  timer_mode_extend_complete:
    c_score_motor: disable

################################## Light Player - turn off pop lights while motor running

light_player:
  start_bonus_count:
    pop_lights: off
  timer_mode_extend_complete:
    pop_lights: on