#config_version=5
# GEMINI 

lights:

################################## Playfield 

  l_red_1:
    number: 0-1
    default_on_color: f5f5f5
  l_red_2:
    number: 0-1
    default_on_color: f5f5f5
  l_white_1:
    number: 0-1
    default_on_color: f5f5f5
  l_white_2:
    number: 0-1
    default_on_color: f5f5f5
  l_white_3:
    number: 0-1
    default_on_color: f5f5f5
  l_green_1:
    number: 0-1
    default_on_color: f5f5f5
  l_green_2:
    number: 0-1
    default_on_color: f5f5f5
  l_green_3:
    number: 0-1
    default_on_color: f5f5f5
  l_yellow_1:
    number: 0-1
    default_on_color: f5f5f5
  l_yellow_2:
    number: 0-1
    default_on_color: f5f5f5
  l_extra_ball:
    number: 0-1
    default_on_color: f5f5f5
  l_special:
    number: 0-1
    default_on_color: f5f5f5
  l_red_star:
    number: 0-1
    default_on_color: f5f5f5
  l_white_star:
    number: 0-1
    default_on_color: f5f5f5
  l_green_star:
    number: 0-1
    default_on_color: f5f5f5
  l_yellow_star:
    number: 0-1
    default_on_color: f5f5f5

  l_shootagain:
    number: 33 
    default_on_color: f5f5f5
  l_extra_ball:
    number: 33 
    default_on_color: f5f5f5
  l_special:
    number: 33 
    default_on_color: f5f5f5

  l_bonus_1:
    number: 33 
    default_on_color: f5f5f5
  l_bonus_2:
    number: 33 
    default_on_color: f5f5f5
  l_bonus_3:
    number: 33 
    default_on_color: f5f5f5
  l_bonus_4:
    number: 33 
    default_on_color: f5f5f5
  l_bonus_5:
    number: 33 
    default_on_color: f5f5f5
  l_bonus_6:
    number: 33 
    default_on_color: f5f5f5
  l_bonus_7:
    number: 33 
    default_on_color: f5f5f5
  l_bonus_8:
    number: 33 
    default_on_color: f5f5f5
  l_bonus_9:
    number: 33 
    default_on_color: f5f5f5
  l_bonus_10:
    number: 33 
    default_on_color: f5f5f5

  l_bonus_2x:
    number: 33 
    default_on_color: f5f5f5
  l_bonus_3x:
    number: 33 
    default_on_color: f5f5f5
  
  l_gi_pf:                        # multiple lights
    number: 33 
    default_on_color: f5f5f5

################################## Backbox

  l_gi_bb:                        # multiple lights
    number: 33 
    default_on_color: f5f5f5

  l_match_00:
    number: 33 
    default_on_color: f5f5f5
  l_match_00:
    number: 33 
    default_on_color: f5f5f5
  l_match_10:
    number: 33 
    default_on_color: f5f5f5
  l_match_20:
    number: 33 
    default_on_color: f5f5f5
  l_match_30:
    number: 33 
    default_on_color: f5f5f5
  l_match_40:
    number: 33 
    default_on_color: f5f5f5
  l_match_50:
    number: 33 
    default_on_color: f5f5f5
  l_match_60:
    number: 33 
    default_on_color: f5f5f5
  l_match_70:
    number: 33 
    default_on_color: f5f5f5
  l_match_80:
    number: 33 
    default_on_color: f5f5f5
  l_match_90:
    number: 33 
    default_on_color: f5f5f5
  
  l_bip_1:
    number: 33 
    default_on_color: f5f5f5
  l_bip_2:
    number: 33 
    default_on_color: f5f5f5
  l_bip_3:
    number: 33 
    default_on_color: f5f5f5
  l_bip_4:
    number: 33 
    default_on_color: f5f5f5
  l_bip_5:
    number: 33 
    default_on_color: f5f5f5

  l_game_over:
    number: 33 
    default_on_color: f5f5f5
  l_tilt:
    number: 33 
    default_on_color: f5f5f5
  l_shootagain:
    number: 33 
    default_on_color: f5f5f5

  l_player1:              # multiple lights for score reels
    number: 33 
    default_on_color: f5f5f5

  l_player2:              # multiple lights for score reels
    number: 33 
    default_on_color: f5f5f5
  
  l_player1_rollover:
    number: 33 
    default_on_color: f5f5f5
  l_player2_rollover:
    number: 33 
    default_on_color: f5f5f5