#config_version=5
# GEMINI 

score_reels:
  score_player_1_10:
    coil_inc: c_player_1_10
    switch_0: s_player_1_10
    rollover: True
    limit_hi: 9
    limit_lo: 0
    repeat_pulse_time: 350ms
    hw_confirm_time: 20ms
  score_player_1_100:
    coil_inc: c_player_1_100
    switch_0: s_player_1_100
    rollover: True
    limit_hi: 9
    limit_lo: 0
    repeat_pulse_time: 350ms
    hw_confirm_time: 20ms
  score_player_1_1000:
    coil_inc: c_player_1_1000
    switch_0: s_player_1_1000
    rollover: True
    limit_hi: 9
    limit_lo: 0
    repeat_pulse_time: 350ms
    hw_confirm_time: 20ms
  score_player_1_10000:
    coil_inc: c_player_1_10000
    switch_0: s_player_1_10000
    rollover: True
    limit_hi: 9
    limit_lo: 0
    repeat_pulse_time: 350ms
    hw_confirm_time: 20ms
  score_player_2_10:
    coil_inc: c_player_2_10
    switch_0: s_player_2_10
    rollover: True
    limit_hi: 9
    limit_lo: 0
    repeat_pulse_time: 350ms
    hw_confirm_time: 20ms
  score_player_2_100:
    coil_inc: c_player_2_100
    switch_0: s_player_2_100
    rollover: True
    limit_hi: 9
    limit_lo: 0
    repeat_pulse_time: 350ms
    hw_confirm_time: 20ms
  score_player_2_1000:
    coil_inc: c_player_2_1000
    switch_0: s_player_2_1000
    rollover: True
    limit_hi: 9
    limit_lo: 0
    repeat_pulse_time: 350ms
    hw_confirm_time: 20ms
  score_player_2_10000:
    coil_inc: c_player_2_10000
    switch_0: s_player_2_10000
    rollover: True
    limit_hi: 9
    limit_lo: 0
    repeat_pulse_time: 350ms
    hw_confirm_time: 20ms

score_reel_groups:
  player1_reels:
    reels: score_player_1_10000, score_player_1_1000, score_player_1_100, score_player_1_10, None
    tags: player1
    max_simultaneous_coils: 3
    chimes: c_chime_10, c_chime_1000, c_chime_100, c_chime_10, none
  player2_reels:
    reels: score_player_2_10000, score_player_2_1000, score_player_2_100, score_player_2_10, None
    tags: player2
    max_simultaneous_coils: 3
    chimes: c_chime_10, c_chime_1000, c_chime_100, c_chime_10, none
