#config_version=6
# GEMINI 

score_reels:
  score_player_1_10:
    coil_inc: c_player_1_10
    switch_0: s_player_1_10
    limit_hi: 9
    limit_lo: 0
    repeat_pulse_time: 120ms
    hw_confirm_time: 10ms
  score_player_1_100:
    coil_inc: c_player_1_100
    switch_0: s_player_1_100
    limit_hi: 9
    limit_lo: 0
    repeat_pulse_time: 120ms
    hw_confirm_time: 10ms
  score_player_1_1000:
    coil_inc: c_player_1_1000
    switch_0: s_player_1_1000
    limit_hi: 9
    limit_lo: 0
    repeat_pulse_time: 120ms
    hw_confirm_time: 10ms
  score_player_1_10000:
    coil_inc: c_player_1_10000
    switch_0: s_player_1_10000
    limit_hi: 9
    limit_lo: 0
    repeat_pulse_time: 120ms
    hw_confirm_time: 10ms
  score_player_2_10:
    coil_inc: c_player_2_10
    switch_0: s_player_2_10
    limit_hi: 9
    limit_lo: 0
    repeat_pulse_time: 120ms
    hw_confirm_time: 10ms
  score_player_2_100:
    coil_inc: c_player_2_100
    switch_0: s_player_2_100
    limit_hi: 9
    limit_lo: 0
    repeat_pulse_time: 120ms
    hw_confirm_time: 10ms
  score_player_2_1000:
    coil_inc: c_player_2_1000
    switch_0: s_player_2_1000
    limit_hi: 9
    limit_lo: 0
    repeat_pulse_time: 120ms
    hw_confirm_time: 10ms
  score_player_2_10000:
    coil_inc: c_player_2_10000
    switch_0: s_player_2_10000
    limit_hi: 9
    limit_lo: 0
    repeat_pulse_time: 120ms
    hw_confirm_time: 10ms

score_reel_groups:
  player1_reels:
    reels: score_player_1_10000, score_player_1_1000, score_player_1_100, score_player_1_10, None
    tags: player1
    debug: true
    file_log: full
    lights_tag: reel1_lights
    chimes: none, c_chime_1000, c_chime_100, c_chime_10, none
  player2_reels:
    reels: score_player_2_10000, score_player_2_1000, score_player_2_100, score_player_2_10, None
    tags: player2
    lights_tag: reel2_lights
    chimes: none, c_chime_1000, c_chime_100, c_chime_10, none
