#config_version=6
#  GEMINI

switches:

################################## Cabinet

                        #SW-16 board 1 bank 1
  s_left_flipper:           #blue/blk
    number: A1-B1-0
    tags: left_flipper
  s_right_flipper:          #blue/white
    number: A1-B1-1
    tags: right_flipper
  s_start:                  #blue/yellow
    number: A1-B1-2
    tags: start
  s_tiltbob:                #blue
    number: A1-B1-3
    tags: tilt_warning

                        #SW-16 board 1 bank 0
  s_balls_per_game:         #orange/black
    number: A1-B0-0
  s_game_mode:              #orange/white
    number: A1-B0-1
  s_replay_level:           #orange/blue
    number: A1-B0-2
  s_chimes_mode:            #orange/yellow
    number: A1-B0-3

################################## Playfield 

                       #SW-16 board 2 bank 0

  s_red_1:            #blue/red
    number: A2-B0-0
    tags: skill_cancel, reds
  s_white_1:            #blue/grey
    number: A2-B0-1
    tags: skill_cancel, whites
  s_green_1:            #blue/green
    number: A2-B0-2
    tags: skill_cancel, greens
  s_yellow_1:            #blue/yellow
    number: A2-B0-3
    tags: skill_cancel, yellows
  s_green_3:               #blue
    number: A2-B0-4
    tags: skill_cancel, greens
  s_left_pop:            #blue/black
    number: A2-B0-5
    tags: skill_cancel, pops
  s_right_pop:            #blue/white
    number: A2-B0-6
    tags: skill_cancel, pops

                       #SW-16 board 2 bank 1
  s_dingwalls1:             #white/blue
    number: A2-B1-0
    tags: skill_cancel, dingwalls
  s_red_2:             #white/orange
    number: A2-B1-1
    tags: skill_cancel, reds
  s_white_2:             #white/green
    number: A2-B1-2
    tags: skill_cancel, whites
  s_white_left:             #white/black
    number: A2-B1-3
    tags: skill_cancel
  s_white_right:             #white
    number: A2-B1-4
    tags: skill_cancel
  s_red_left:             #white/yellow
    number: A2-B1-5
    tags: skill_cancel
  s_red_right:             #white/red
    number: A2-B1-6
    tags: skill_cancel

                       #SW-16 board 3 bank 0
  s_green_left:             #yellow/green
    number: A3-B0-0
    tags: skill_cancel
  s_green_right:             #yellow/orange
    number: A3-B0-1
    tags: skill_cancel
  s_yellow_left:             #yellow
    number: A3-B0-2
    tags: skill_cancel
  s_yellow_right:             #yellow/white
    number: A3-B0-3
    tags: skill_cancel
  s_yellow_2:             #yellow/black
    number: A3-B0-4
    tags: skill_cancel, yellows
  s_green_2:             #yellow/purple
    number: A3-B0-5
    tags: skill_cancel, greens
  s_dingwalls2:             #yellow/blue
    number: A3-B0-6
    tags: skill_cancel, dingwalls
  s_special:             #yellow/red
    number: A3-B0-7
    tags: skill_cancel

                       #SW-16 board 3 bank 1

  s_drain:             #grey
    number: A3-B1-0
    tags: drain
  s_extra_ball:             #grey/orange
    number: A3-B1-1
    tags: skill_cancel
  s_white_3:             #grey/red
    number: A3-B1-2
    tags: skill_cancel, whites
  s_left_sling:             #grey/blue
    number: A3-B1-3
    tags: skill_cancel
  s_right_sling:             #grey/black
    number: A3-B1-4
    tags: skill_cancel

################################## Backbox

                       #SW-16 board 0 bank 0

  s_player_1_10000:
    number: A0-B0-0         #white/orange
  s_player_1_1000:
    number: A0-B0-1         #white/green
  s_player_1_100:
    number: A0-B0-2         #white/yellow
  s_player_1_10:
    number: A0-B0-3         #white/black

                       #SW-16 board 0 bank 1

  s_player_2_10000:
    number: A0-B1-4         #grey/orange
  s_player_2_1000:
    number: A0-B1-5         #grey/white
  s_player_2_100:
    number: A0-B1-6         #grey/yellow
  s_player_2_10:
    number: A0-B1-7         #grey/black

  s_credit_down:              
    number: A0-B1-0         #orange/yellow
  s_credit_up:
    number: A0-B1-1         #orange/black