#config_version=6
# GEMINI 

mode:
  start_events: special_lit
  stop_events: ball_ending
  priority: 200


shots:
  shot_special:
    switch: s_special
    reset_events: mode_special_started
    profile: p_onoff
    show_tokens:
      led: l_special
  shot_special2:
    switch: s_special
    reset_events: mode_special_started
    profile: p_offon
    show_tokens:
      leds: l_shoot_again, l_shoot_again_bb