#config_version=6
# GEMINI

tilt:
    tilt_warning_events: s_tiltbob_active
    tilt_warning_switch_tag: tilt_warning
    warnings_to_tilt: 3
    reset_warnings_events: ball_ended
    multiple_hit_window: 400ms
    settle_time: 5s
