#config_version=5
##! mode: match
# GEMINI 

mode:
    start_events: game_ending
    code: match.Match
    use_wait_queue: true
    priority: 1000

queue_relay_player:
  match_no_match:
    post: no_match
    wait_for: slide_no_match_slide_removed
    pass_args: true
  match_has_match:
    post: has_match
    wait_for: slide_match_slide_removed
    pass_args: true

mode_settings:
  non_match_number_step: 10

slide_player:
  no_match:
    no_match_slide:
      expire: 3s
  has_match:
    match_slide:
      expire: 3s

slides:
  match_slide:
    - type: text
      text: "Match number: (winner_number)"
  no_match_slide:
    - type: text
      text: "Match number: (winner_number)"

