#config_version=6
##! mode: match
# GEMINI 

mode:
    start_events: game_will_end
    use_wait_queue: true
    priority: 1000

queue_relay_player:
  game_ending:
    post: at_match
    wait_for: machine_var_match_number

mode_settings:
  non_match_number_step: 10
